server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://antonio-dev.go.ro:15772/onlyFeetDb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    drop-first: false # Drops and creates scheme from scratch on every start
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://antonio-dev.go.ro:8081/keycloak-app/realms/onlyFeet-realm

  mail:
    host: smtp.gmail.com
    port: 587
    username: onlyFeet.app@gmail.com
    password: pvdersnsbpiqzzip
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

keycloak:
  realm: onlyFeet-realm
  resource: onlyFeet-backend
  # auth-server-url: http://antonio-dev.go.ro:8081/keycloack-app/realms/gym-management-realm/protocol/openid-connect/auth
  auth-server-url: http://antonio-dev.go.ro:8081/keycloak-app/
  credentials:
    secret: PXMyEtADl5nCpj7efKiVjk81ImIJgo9y
  admin:
    username: admin
    password: admin

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173,http://antonio-dev.go.ro:8081"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

upload:
  dir: uploads/

external-link:
  url: "http://localhost:8080/images/"
  #url: "http://antonio-dev.go.ro:8081/dentatrack-api/images/"

media:
  upload:
    dir: uploads
  public:
    url:
      prefix: http://localhost:8080/uploads/

stripe:
  secret:
    key:
  webhook:
    secret:

frontend:
  success:
    url: https://yourfrontend.com/payment/success
  cancel:
    url: https://yourfrontend.com/payment/cancel
